cable:
  cable_user%CLIMATE_fromZero: .FALSE.
  cable_user%YearStart: 1901
  cable_user%YearEnd: 2022
  icycle: 2
  spincasa: .FALSE.
  cable_user%CASA_fromZero: .FALSE.
  cable_user%CASA_DUMP_READ: .FALSE.
  cable_user%CASA_DUMP_WRITE: .FALSE.
  cable_user%CASA_SPIN_STARTYEAR: 1850
  cable_user%CASA_SPIN_ENDYEAR: 1859
  cable_user%limit_labile: .FALSE.
  cable_user%POP_fromZero: .FALSE.
  cable_user%POP_out: "ini"
  cable_user%POPLUC: .TRUE.
  cable_user%POPLUC_RunType: "static"
luc:
  YearStart: 1901
  YearEnd: 2022
cru:
  Run: "S0_TRENDY"
