cable:
  cable_user%CLIMATE_fromZero: .FALSE.
  cable_user%YearStart: 1841
  cable_user%YearEnd: 1860
  icycle: 12
  spincasa: .TRUE.
  cable_user%CASA_fromZero: .FALSE.
  cable_user%CASA_DUMP_READ: .TRUE.
  cable_user%CASA_DUMP_WRITE: .FALSE.
  cable_user%CASA_SPIN_STARTYEAR: 1841
  cable_user%CASA_SPIN_ENDYEAR: 1860
  cable_user%limit_labile: .FALSE.
  cable_user%POP_fromZero: .FALSE.
  cable_user%POP_out: "ini"
  cable_user%POPLUC: .TRUE.
  cable_user%POPLUC_RunType: "static"
luc:
cru:
