cable:
  cable_user%CLIMATE_fromZero: .FALSE.
  cable_user%YearStart: 1580
  cable_user%YearEnd: 1699
  icycle: 12
  spincasa: .FALSE.
  cable_user%CASA_OUT_FREQ: "annually"
  cable_user%CASA_fromZero: .FALSE.
  cable_user%CASA_DUMP_READ: .TRUE.
  cable_user%CASA_DUMP_WRITE: .FALSE.
  cable_user%CASA_SPIN_STARTYEAR: 1841
  cable_user%CASA_SPIN_ENDYEAR: 1860
  cable_user%limit_labile: .FALSE.
  cable_user%POP_fromZero: .FALSE.
  cable_user%POP_out: "ini"
  cable_user%POPLUC: .TRUE.
  cable_user%POPLUC_RunType: "init"
  cable_user%LUC_restart_in: ""
  cable_user%c13o2_restart_in_luc: ""
luc:
  YearStart: 1580
  YearEnd: 1699
cru:

